patreon: hipersayanx
ko_fi: hipersayanx
liberapay: hipersayanx
custom: ["https://www.paypal.me/WebcamoidDonations", "https://commerce.coinbase.com/checkout/0287d8a2-0c49-4e8e-9ae1-a3d1e59f3931", "https://gist.github.com/hipersayanX/0d575fc7b9b36a2e9817027fb50258bd"]
