language: cpp

addons:
  apt:
    update: true

env:
  global:
    - QTIFWVER=4.0.0
    # BT_KEY
    - secure: "jpAdFkDOmltToCv20sTD0mfavylXQo3g/rFD62bK2jTBX0xZ+PCFGP0MGdxl15RckD4FbP6M64tQLiHFP/qS93gItbQTZF4o+rA2bmLyycvshSdMYi1j8qCO1yJ7ZAMi59Ni/F6L1o8QP48vwJlx6veTY5SRg9adnBJsdnluOhTZBnI2sMJ07dnrq6byWKcQvvQCoErKWAbnauao7VzKb+L4oKmXimqkNbMld7NX0MBP29OARYlhFXItVsJuZ1J6lCUn+upVvMP4QsMO9wZxhbu0DiVLYOWUAA8coYocQxbnNH8+3bX7UJqZ3ARDwrXMQUcW3oaVa9S9XlWfDFdhr0B/hHwjHoC0cxVfH+Ik1U661fjtK4pp34mpt+99T6sFlDB4Xr1yh9LAOj1UAdywG93anlL5DaSCv1XKEJNJg+v9PAL8mltCfJmzaxsfWQt+MUUejLbrmd7sk8qXJIlO5GA20ONsAzYQpcEsxKryzmyB6H5PqtnozvpzqPoXIopTJZ6fR/lTQ/8LvmEM0+2bbpqY7vnBSjsAq1IRHuG0VfYaxr1dV/rGQ7Bybsu1fLHNMr6bujKQOlJJ5xJakejKIklu3NB9WTEjO/vJupBrzROCHKes/L0hktKypLmpKXihKJWLfMHU57dW8ZX9mLHfypBg8c57uGVhTG5rC43jZHs="

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.243
      - KERNEL_VERSION=4.4.243-0404243
      - KERNEL_VERSION_C=202011102158
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.243
      - KERNEL_VERSION=4.9.238-0409243
      - KERNEL_VERSION_C=202011102221
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.206
      - KERNEL_VERSION=4.14.206-0414206
      - KERNEL_VERSION_C=202011102209
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=focal
      - REPOSITORY=v4.19.157
      - KERNEL_VERSION=4.19.157-0419157
      - KERNEL_VERSION_C=202011102159
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=focal
      - REPOSITORY=v5.4.77
      - KERNEL_VERSION=5.4.77-050477
      - KERNEL_VERSION_C=202011101641
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.8.18
      - KERNEL_VERSION=5.8.18-050818
      - KERNEL_VERSION_C=202011011237
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.9.8
      - KERNEL_VERSION=5.9.8-050908
      - KERNEL_VERSION_C=202011101634
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

before_install:
  - sudo apt-get install -qq -y curl wget libxkbcommon-x11-0
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

after_success:
  - chmod +x ports/ci/travis/deploy.sh
  - ports/ci/travis/deploy.sh
  - chmod +x ports/ci/travis/upload.sh
  - ports/ci/travis/upload.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
