language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.243
      - KERNEL_VERSION=4.4.243-0404243
      - KERNEL_VERSION_C=202011102158
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.243
      - KERNEL_VERSION=4.9.238-0409243
      - KERNEL_VERSION_C=202011102221
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.206
      - KERNEL_VERSION=4.14.206-0414206
      - KERNEL_VERSION_C=202011102209
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=focal
      - REPOSITORY=v4.19.157
      - KERNEL_VERSION=4.19.157-0419157
      - KERNEL_VERSION_C=202011102159
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=focal
      - REPOSITORY=v5.4.77
      - KERNEL_VERSION=5.4.77-050477
      - KERNEL_VERSION_C=202011101641
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.8.18
      - KERNEL_VERSION=5.8.18-050818
      - KERNEL_VERSION_C=202011011237
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.9.8
      - KERNEL_VERSION=5.9.8-050908
      - KERNEL_VERSION_C=202011101634
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

before_install:
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

after_success:
  - chmod +x ports/ci/travis/deploy.sh
  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
