language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.16.81
      - KERNEL_VERSION=3.16.81-031681
      - KERNEL_VERSION_C=202001110932
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.211
      - KERNEL_VERSION=4.4.211-0404211
      - KERNEL_VERSION_C=202001230339
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.211
      - KERNEL_VERSION=4.9.211-0409211
      - KERNEL_VERSION_C=202001230833
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.167
      - KERNEL_VERSION=4.14.167-0414167
      - KERNEL_VERSION_C=202001230928
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v4.19.98
      - KERNEL_VERSION=4.19.98-041998
      - KERNEL_VERSION_C=202001230334
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=focal
      - REPOSITORY=v5.4.14
      - KERNEL_VERSION=5.4.14-050414
      - KERNEL_VERSION_C=202001230832
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

before_install:
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

#after_success:
#  - chmod +x ports/ci/travis/deploy.sh
#  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
