language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v3.16.85
      - KERNEL_VERSION=3.16.85-031685
      - KERNEL_VERSION_C=202006111533
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=xenial
      - REPOSITORY=v4.4.227
      - KERNEL_VERSION=4.4.227-0404227
      - KERNEL_VERSION_C=202006110834
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.9.227
      - KERNEL_VERSION=4.9.227-0409227
      - KERNEL_VERSION_C=202006110433
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=bionic
      - REPOSITORY=v4.14.184
      - KERNEL_VERSION=4.14.184-0414184
      - KERNEL_VERSION_C=202006110833
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=disco
      - REPOSITORY=v4.19.128
      - KERNEL_VERSION=4.19.128-0419128
      - KERNEL_VERSION_C=202006101632
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.4.46
      - KERNEL_VERSION=5.4.46-050446
      - KERNEL_VERSION_C=202006101938
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.6.18
      - KERNEL_VERSION=5.6.18-050618
      - KERNEL_VERSION_C=202006101539
      - UNSIGNED_IMG=1
      - NEED_MODULES=1
      - export USE_QEMU=1
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - SYSTEM_VERSION=groovy
      - REPOSITORY=v5.7.2
      - KERNEL_VERSION=5.7.2-050702
      - KERNEL_VERSION_C=202006101934
      - UNSIGNED_IMG=1
      - NEED_MODULES=1

before_install:
  - docker pull ubuntu:${SYSTEM_VERSION}
  - docker ps -a
  - docker run --privileged -it -d -v ${PWD}:/sources -w /sources --name ubuntu ubuntu:${SYSTEM_VERSION} /bin/sh
  - export EXEC="docker exec ubuntu"
  - export SYSTEM_ARCH=amd64

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

#after_success:
#  - chmod +x ports/ci/travis/deploy.sh
#  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
