name: Linux Ubuntu

on: [push, pull_request]

env:
  QTIFWVER: 4.5.2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         # Do not update
         - dockerimg: amd64/ubuntu:bionic
           repository: v4.14.215
           kernel_version: 4.14.215-0414215
           kernel_version_c: 202101122110
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 1
         - dockerimg: amd64/ubuntu:focal
           repository: v4.19.283
           kernel_version: 4.19.283-0419283
           kernel_version_c: 202305171050
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         - dockerimg: amd64/ubuntu:focal
           repository: v5.4.243
           kernel_version: 5.4.243-0504243
           kernel_version_c: 202305171043
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         # Do not update
         - dockerimg: amd64/ubuntu:jammy
           repository: v5.10.130
           kernel_version: 5.10.130-0510130
           kernel_version_c: 202207121545
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         - dockerimg: amd64/ubuntu:jammy
           repository: v5.15.113
           kernel_version: 5.15.113-0515113
           kernel_version_c: 202305241341
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         - dockerimg: amd64/ubuntu:lunar
           repository: v6.1.30
           kernel_version: 6.1.30-060130
           kernel_version_c: 202305241736
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         - dockerimg: amd64/ubuntu:lunar
           repository: v6.2.16
           kernel_version: 6.2.16-060216
           kernel_version_c: 202305171336
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
         - dockerimg: amd64/ubuntu:lunar
           repository: v6.3.4
           kernel_version: 6.3.4-060304
           kernel_version_c: 202305241735
           unsigned_img: 1
           need_modules: 1
           use_qemu: 0
           upload: 0
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ matrix.dockerimg }}
        options: >-
          --privileged
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e DOCKERIMG=${{ matrix.dockerimg }}
          -e REPOSITORY=${{ matrix.repository }}
          -e KERNEL_VERSION=${{ matrix.kernel_version }}
          -e KERNEL_VERSION_C=${{ matrix.kernel_version_c }}
          -e UNSIGNED_IMG=${{ matrix.unsigned_img }}
          -e NEED_MODULES=${{ matrix.need_modules }}
          -e USE_QEMU=${{ matrix.use_qemu }}
          -e QTIFWVER=${{ env.QTIFWVER }}
          -e UPLOAD=${{ matrix.upload }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux/install_deps.sh
          ./ports/ci/linux/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/linux/build.sh
          ./ports/ci/linux/build.sh
          echo
          echo Test module
          echo
          chmod +x ports/ci/linux/test.sh
          ./ports/ci/linux/test.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/linux/deploy.sh
          ./ports/ci/linux/deploy.sh
    - name: Daily build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ matrix.dockerimg }}
        options: >-
          --privileged
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e DOCKERIMG=${{ matrix.dockerimg }}
          -e REPOSITORY=${{ matrix.repository }}
          -e KERNEL_VERSION=${{ matrix.kernel_version }}
          -e KERNEL_VERSION_C=${{ matrix.kernel_version_c }}
          -e UNSIGNED_IMG=${{ matrix.unsigned_img }}
          -e NEED_MODULES=${{ matrix.need_modules }}
          -e USE_QEMU=${{ matrix.use_qemu }}
          -e QTIFWVER=${{ env.QTIFWVER }}
          -e UPLOAD=${{ matrix.upload }}
          -e DAILY_BUILD=1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux/install_deps.sh
          ./ports/ci/linux/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/linux/build.sh
          ./ports/ci/linux/build.sh
          echo
          echo Test module
          echo
          chmod +x ports/ci/linux/test.sh
          ./ports/ci/linux/test.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/linux/deploy.sh
          ./ports/ci/linux/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        files: packages-v4.14/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v1
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        body: "${{ github.event.head_commit.message }} (commit: ${{ github.sha }})<hr>**Note**: Ignore the commit information of the tag, the files in the release keep updating with every new build, these packages were built from ${{ github.sha }} commit."
        prerelease: true
        files: packages-v4.14/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
