name: Linux Ubuntu

on: [push, pull_request]

env:
  QTIFWVER: 4.4.2
  SYSTEM_ARCH: amd64

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - system_version: bionic
           repository: v4.9.330
           kernel_version: 4.9.330-0409330
           kernel_version_c: 202209280940
           use_qemu: 1
           upload: 1
         - system_version: bionic
           repository: v4.14.295
           kernel_version: 4.14.295-0414295
           kernel_version_c: 202209280542
           unsigned_img: 1
           need_modules: 1
           use_qemu: 1
         - system_version: focal
           repository: v4.19.260
           kernel_version: 4.19.260-0419260
           kernel_version_c: 202209281119
           unsigned_img: 1
           need_modules: 1
         - system_version: focal
           repository: v5.4.215
           kernel_version: 5.4.215-0504215
           kernel_version_c: 202209280647
           unsigned_img: 1
           need_modules: 1
         - system_version: jammy
           repository: v5.10.146
           kernel_version: 5.10.146-0510146
           kernel_version_c: 202209281128
           unsigned_img: 1
           need_modules: 1
         - system_version: jammy
           repository: v5.15.71
           kernel_version: 5.15.71-051571
           kernel_version_c: 202209281049
           unsigned_img: 1
           need_modules: 1
         - system_version: kinetic
           repository: v5.19.12
           kernel_version: 5.19.12-051912
           kernel_version_c: 202209281047
           unsigned_img: 1
           need_modules: 1
    steps:
    - uses: actions/checkout@v2
    - name: Release build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ubuntu:${{ matrix.system_version }}
        options: >-
          --privileged
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e SYSTEM_VERSION=${{ matrix.system_version }}
          -e SYSTEM_ARCH=${{ env.SYSTEM_ARCH }}
          -e REPOSITORY=${{ matrix.repository }}
          -e KERNEL_VERSION=${{ matrix.kernel_version }}
          -e KERNEL_VERSION_C=${{ matrix.kernel_version_c }}
          -e UNSIGNED_IMG=${{ matrix.unsigned_img }}
          -e NEED_MODULES=${{ matrix.need_modules }}
          -e USE_QEMU=${{ matrix.use_qemu }}
          -e QTIFWVER=${{ env.QTIFWVER }}
          -e UPLOAD=${{ matrix.upload }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux/install_deps.sh
          ./ports/ci/linux/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/linux/build.sh
          ./ports/ci/linux/build.sh
          echo
          echo Test module
          echo
          chmod +x ports/ci/linux/test.sh
          ./ports/ci/linux/test.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/linux/deploy.sh
          ./ports/ci/linux/deploy.sh
    - name: Daily build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ubuntu:${{ matrix.system_version }}
        options: >-
          --privileged
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ env.GITHUB_REF }}
          -e GITHUB_SERVER_URL=${{ env.GITHUB_SERVER_URL }}
          -e GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}
          -e GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          -e SYSTEM_VERSION=${{ matrix.system_version }}
          -e SYSTEM_ARCH=${{ env.SYSTEM_ARCH }}
          -e REPOSITORY=${{ matrix.repository }}
          -e KERNEL_VERSION=${{ matrix.kernel_version }}
          -e KERNEL_VERSION_C=${{ matrix.kernel_version_c }}
          -e UNSIGNED_IMG=${{ matrix.unsigned_img }}
          -e NEED_MODULES=${{ matrix.need_modules }}
          -e USE_QEMU=${{ matrix.use_qemu }}
          -e QTIFWVER=${{ env.QTIFWVER }}
          -e UPLOAD=${{ matrix.upload }}
          -e DAILY_BUILD=1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux/install_deps.sh
          ./ports/ci/linux/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/linux/build.sh
          ./ports/ci/linux/build.sh
          echo
          echo Test module
          echo
          chmod +x ports/ci/linux/test.sh
          ./ports/ci/linux/test.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/linux/deploy.sh
          ./ports/ci/linux/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v0.1.6
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        files: packages-v4.9/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Daily Build Upload
      uses: softprops/action-gh-release@v0.1.6
      if: ${{ !startsWith(github.ref, 'refs/tags/') && matrix.upload }}
      with:
        body: "${{ github.event.head_commit.message }} (commit: ${{ github.sha }})"
        prerelease: true
        files: packages-v4.9/*
        name: Daily Build
        tag_name: daily-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
